Send register event to client and set cookie on registration or text …
Quiq/quiq-chat pull request #15
Opened 2017-07-21 22:40 UTC by drewjenkins

…websocket message

2017-07-23 23:16 UTC, natenorberg commented on package.json
> +  "version": "1.7.2",
Should this be a minor version bump since you're adding a method?

2017-07-24 14:27 UTC, fredvollmer requested changes
Nice. I guess I hadn't really thought about the fact that the parent window continues to receive and process web socket messages. Seems like a solid solution!

2017-07-24 14:27 UTC, fredvollmer commented on src/QuiqChatClient.js
> +  };
Is this getting a little specific for QuiqChatCleint? Can we rename it to` onRegister`? It's a small issue, but in my mind we want to try and keep QuiqChatClient as general as possible...

2017-07-24 15:11 UTC, drewjenkins commented on src/QuiqChatClient.js
> +  };
Good call, will update name

2017-07-24 15:27 UTC, drewjenkins commented on package.json
> +  "version": "1.7.2",
Ah yeah you are right.  I was thinking minor was for changes that may break, and nano for ones that wouldn't. Will fix

2017-07-24 15:48 UTC, merged